trigger:
- main

pool:
  name: self-hosted-agent

variables:
  APP_PATH: '/chatapp'
  ARTIFACT_NAME: 'chatapp-package'

stages:
- stage: PackageAndPublish
  jobs:
  - job: PackageJob
    steps:

    - checkout: self
      clean: true

    - script: |
        echo "Zipping code..."
        zip -r $(ARTIFACT_NAME).zip ./*
      displayName: 'Package code as ZIP'

    - publish: $(ARTIFACT_NAME).zip
      artifact: $(ARTIFACT_NAME)
      displayName: 'Publish artifact'
