trigger:
- main

pool:
  name: SelfHostedBackend  # your self-hosted agent pool name

variables:
  VM_USER: 'azureuser'
  VM_IP: '20.115.90.142'
  SSH_KEY_PATH: '/home/azureuser/.ssh/backend_key.pem'
  APP_DIR: '/chatapp'

stages:
- stage: Deploy
  displayName: '🚀 Deploy to Backend VM'
  jobs:
  - job: PushAndDeploy
    displayName: 'Copy, Install & Migrate'
    steps:

    - script: |
        echo "Copying application files to backend..."
        rsync -avz -e "ssh -i $(SSH_KEY_PATH) -o StrictHostKeyChecking=no" $(Build.SourcesDirectory)/ $(VM_USER)@$(VM_IP):$(APP_DIR)
      displayName: 'Copy application files to backend'

    - script: |
        echo "Installing Python dependencies..."
        ssh -i $(SSH_KEY_PATH) -o StrictHostKeyChecking=no $(VM_USER)@$(VM_IP) "
          cd $(APP_DIR) && \
          source venv/bin/activate && \
          pip install -r requirements.txt
        "
      displayName: 'Install Python dependencies'

    - script: |
        echo "Running Django makemigrations & migrate..."
        ssh -i $(SSH_KEY_PATH) -o StrictHostKeyChecking=no $(VM_USER)@$(VM_IP) "
          cd $(APP_DIR)/fundoo && \
          source ../venv/bin/activate && \
          python3 manage.py makemigrations && \
          python3 manage.py migrate
        "
      displayName: 'Run Django makemigrations & migrate'

    - script: |
        echo "Restarting chatappdaemon.service..."
        ssh -i $(SSH_KEY_PATH) -o StrictHostKeyChecking=no $(VM_USER)@$(VM_IP) "sudo systemctl restart chatappdaemon.service"
      displayName: 'Restart chatappdaemon.service'
