trigger:
- main

pool:
  name: SelfHostedBackend

variables:
  APP_PATH: '/chatapp'
  SERVICE_NAME: 'chatappdaemon.service'

stages:
- stage: Deploy
  jobs:
  - job: DeployJob
    steps:

    - checkout: self
      clean: true

    - task: CopyFilesOverSSH@0
      inputs:
        sshEndpoint: 'backend_vm_ssh'
        sourceFolder: '$(Build.SourcesDirectory)'
        contents: '**'
        targetFolder: '$(APP_PATH)'
      displayName: 'Copy code to backend server'

    - task: SSH@0
      inputs:
        sshEndpoint: 'backend_vm_ssh'
        runOptions: 'inline'
        inline: |
          cd $(APP_PATH)
          source venv/bin/activate
          pip3 install -r requirements.txt
          deactivate
      displayName: 'Install Python dependencies'

    - task: SSH@0
      inputs:
        sshEndpoint: 'backend_vm_ssh'
        runOptions: 'inline'
        inline: |
          cd $(APP_PATH)
          source venv/bin/activate
          cd fundoo
          python3 manage.py migrate
          cd ..
          deactivate
      displayName: 'Run Django migrations'

    - task: SSH@0
      inputs:
        sshEndpoint: 'backend_vm_ssh'
        runOptions: 'inline'
        inline: |
          sudo systemctl restart $(SERVICE_NAME)
      displayName: 'Restart service'
