trigger:
- main

pool:
  name: SelfHostedBackend  # Use your self-hosted agent pool

variables:
  SSH_KEY_PATH: '/home/azureuser/.ssh/backend_key.pem'
  BACKEND_HOST: '20.115.90.142'
  APP_PATH: '/chatapp'
  SERVICE_NAME: 'chatappdaemon.service'

stages:
- stage: Deploy
  jobs:
  - job: DeployJob
    steps:

    - checkout: self
      clean: true

    - script: |
        echo "Copying code to backend server..."
        scp -i $(SSH_KEY_PATH) -o StrictHostKeyChecking=no -r * azureuser@$(BACKEND_HOST):$(APP_PATH)/
      displayName: 'Copy code to backend server'

    - script: |
        echo "Setting up Python virtual environment and installing dependencies..."
        ssh -i $(SSH_KEY_PATH) -o StrictHostKeyChecking=no azureuser@$(BACKEND_HOST) << EOF
          sudo apt-get update
          sudo apt-get install -y libmysqlclient-dev python3-dev build-essential python3-venv
          cd $(APP_PATH)
          if [ ! -d "venv" ]; then
            python3 -m venv venv
          fi
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install python-dotenv mysqlclient
        EOF
      displayName: 'Set up venv & install Python dependencies'

    - script: |
        echo "Running makemigrations..."
        ssh -i $(SSH_KEY_PATH) -o StrictHostKeyChecking=no azureuser@$(BACKEND_HOST) << EOF
          cd $(APP_PATH)
          source venv/bin/activate
          cd fundoo
          python3 manage.py makemigrations
        EOF
      displayName: 'Run makemigrations'

    - script: |
        echo "Applying migrations..."
        ssh -i $(SSH_KEY_PATH) -o StrictHostKeyChecking=no azureuser@$(BACKEND_HOST) << EOF
          cd $(APP_PATH)
          source venv/bin/activate
          cd fundoo
          python3 manage.py migrate
        EOF
      displayName: 'Apply migrations'

    - script: |
        echo "Restarting service $(SERVICE_NAME)..."
        ssh -i $(SSH_KEY_PATH) -o StrictHostKeyChecking=no azureuser@$(BACKEND_HOST) << EOF
          cd $(APP_PATH)
          source venv/bin/activate
          sudo systemctl restart $(SERVICE_NAME)
        EOF
      displayName: 'Restart service'
