trigger:
  - main

pool:
  name: SelfHostedBackend  # Use your self-hosted agent pool or Hosted Ubuntu if you have permission

variables:
  BACKEND_IP: '20.115.90.142'
  SSH_USER: 'azureuser'
  SSH_KEY_PATH: '/home/azureuser/.ssh/backend_key.pem'  # adjust if needed
  APP_DIR: '/chatapp'

stages:
- stage: Deploy
  displayName: '🚀 Deploy to Backend VM'
  jobs:
  - job: PushAndDeploy
    displayName: 'Copy, Install & Migrate'
    steps:
    - script: |
        echo "Copying application files to backend..."
        rsync -avz -e "ssh -i ${SSH_KEY_PATH} -o StrictHostKeyChecking=no" \
          $(Build.SourcesDirectory)/ ${SSH_USER}@${BACKEND_IP}:${APP_DIR}/
      displayName: 'Copy application files to backend'

    - script: |
        echo "Installing Python dependencies..."
        ssh -i ${SSH_KEY_PATH} -o StrictHostKeyChecking=no ${SSH_USER}@${BACKEND_IP} << EOF
          source ${APP_DIR}/venv/bin/activate
          pip install -r ${APP_DIR}/requirements.txt
        EOF
      displayName: 'Install Python dependencies'

    - script: |
        echo "Running Django migrations..."
        ssh -i ${SSH_KEY_PATH} -o StrictHostKeyChecking=no ${SSH_USER}@${BACKEND_IP} << EOF
          source ${APP_DIR}/venv/bin/activate
          cd ${APP_DIR}/fundoo
          python3 manage.py makemigrations
          python3 manage.py migrate
        EOF
      displayName: 'Run Django makemigrations & migrate'

    - script: |
        echo "Restarting chatapp service..."
        ssh -i ${SSH_KEY_PATH} -o StrictHostKeyChecking=no ${SSH_USER}@${BACKEND_IP} sudo systemctl restart chatapp.service
      displayName: 'Restart chatapp.service'
