trigger:
  - main

pool:
  name: SelfHostedBackend

variables:
  APP_DIR: '/app'
  SERVICE_NAME: 'chatapp.service'

stages:
- stage: Deploy
  displayName: 🚀 Deploy to Backend VM
  jobs:
  - job: PushAndDeploy
    displayName: Copy, Install & Migrate
    steps:
    - script: |
        echo "Copying application files to backend..."
        rsync -av --delete $(Build.SourcesDirectory)/ $(APP_DIR)/
      displayName: 'Copy application files to backend'

    - script: |
        echo "Installing Python dependencies..."
        source $(APP_DIR)/venv/bin/activate
        pip install -r $(APP_DIR)/requirements.txt
      displayName: 'Install Python dependencies'

    - script: |
        echo "Running Django makemigrations & migrate..."
        source $(APP_DIR)/venv/bin/activate
        cd $(APP_DIR)/fundoo
        python3 manage.py makemigrations
        python3 manage.py migrate
      displayName: 'Run Django makemigrations & migrate'

    - script: |
        echo "Restarting ${SERVICE_NAME}..."
        sudo systemctl restart ${SERVICE_NAME}
      displayName: 'Restart chatapp service'
      # For sudo to work without password, make sure your backend user has passwordless sudo or configure accordingly

