trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  BACKEND_HOST: '40.0.0.5'
  REPO_URL: 'https://github.com/prateekjain13/chatapp-modified-ubuntu-22.04.git'
  BRANCH: 'main'
  APP_PATH: '/chatapp'
  SERVICE_NAME: 'chatappdaemon.service'

steps:
- checkout: self
  clean: true

# 🔐 Download SSH key securely
- task: DownloadSecureFile@1
  name: sshkey
  inputs:
    secureFile: backend_key.pem

# 🔐 Set permissions on the key so SSH won't reject it
- script: |
    chmod 600 $(sshkey.secureFilePath)
  displayName: 'Set SSH key permissions'

# 🛠️ Deploy to Backend Server
- task: Bash@3
  displayName: 'Deploy ChatApp to Backend Server'
  inputs:
    targetType: 'inline'
    script: |
      set -e

      echo "=== Copying code to backend server... ==="
      git clone --branch $BRANCH $REPO_URL repo
      scp -i $(sshkey.secureFilePath) -o StrictHostKeyChecking=no -r repo/* azureuser@$BACKEND_HOST:$APP_PATH/

      echo "=== Installing Python dependencies... ==="
      ssh -i $(sshkey.secureFilePath) -o StrictHostKeyChecking=no azureuser@$BACKEND_HOST "
        cd $APP_PATH &&
        source venv/bin/activate &&
        pip install -r requirements.txt
      "

      echo "=== Running makemigrations... ==="
      ssh -i $(sshkey.secureFilePath) -o StrictHostKeyChecking=no azureuser@$BACKEND_HOST "
        cd $APP_PATH/fundoo &&
        source $APP_PATH/venv/bin/activate &&
        python3 manage.py makemigrations
      "

      echo "=== Applying migrations... ==="
      ssh -i $(sshkey.secureFilePath) -o StrictHostKeyChecking=no azureuser@$BACKEND_HOST "
        cd $APP_PATH/fundoo &&
        source $APP_PATH/venv/bin/activate &&
        python3 manage.py migrate
      "

      echo "=== Restarting $SERVICE_NAME... ==="
      ssh -i $(sshkey.secureFilePath) -o StrictHostKeyChecking=no azureuser@$BACKEND_HOST "
        sudo systemctl restart $SERVICE_NAME
      "

      echo "=== Deployment complete ==="
